// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC153Z5s5w3MmY9p706Y8GxgW7bqUB-p7k',
    appId: '1:14043213840:web:b1abe4a55816931f979a95',
    messagingSenderId: '14043213840',
    projectId: 'infoapp-24cdd',
    authDomain: 'infoapp-24cdd.firebaseapp.com',
    storageBucket: 'infoapp-24cdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Wv3UAnaYcvxBFUUrMFgmXoFjdKiI-kQ',
    appId: '1:14043213840:android:75eb0199988df268979a95',
    messagingSenderId: '14043213840',
    projectId: 'infoapp-24cdd',
    storageBucket: 'infoapp-24cdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgtPX1ihTwMV1SreO_oFb8ewNv-4TATk',
    appId: '1:14043213840:ios:a7f5ea560927c4da979a95',
    messagingSenderId: '14043213840',
    projectId: 'infoapp-24cdd',
    storageBucket: 'infoapp-24cdd.appspot.com',
    iosBundleId: 'com.example.infoApp',
  );
}
